# Constants

INTRODUCTION = """Welcome to Midnight Rider

WE'VE STOLEN A CAR. WE NEED TO GET IT HOME.
THE CAR IS SPECIAL.

THAT'S WHY THE GOVERNMENT WANTS IT

WE CANNOT LET THEM HAVE IT

GOAL #1 SURVIVAL... AND THE CAR
REACH THE SAFEHOUSE BEFORE THE MEN GETCHU!!!
"""